In [1]:
import numpy as np
np.__version__

'1.22.3'

## Python data types(lists and integer objects)

In [14]:
L = list(range(10))
L1 = [str(c) for c in L]

L,L1

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'])

### Fixed type arrays in Python

In [37]:
import array
arr = array.array('i', [i for i in range(10)])
arr.insert(2, 4)
arr

array('i', [0, 1, 4, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating NumPy arrays

In [53]:
#efficiently perform operations on data while python arrays gives efficient storage facility

nparr1 = np.array([1,2,3,4,5,])
nparr2 = np.array([1.2,3.2,2,8,.5])
nparr1, nparr2                           #arrays of same data type and automatic upcasted by numpy

(array([1, 2, 3, 4, 5]), array([1.2, 3.2, 2. , 8. , 0.5]))

In [35]:
#fix the data type in nparray

nparr3 = np.array([1,2,3,4,], dtype = 'float32')
nparr3, type(nparr3)

(array([1., 2., 3., 4.], dtype=float32), numpy.ndarray)

In [50]:
#Creating Multi-dimensional array using lists of lists(nested lists)

A1 = np.array(range(7))
A2 = np.array([range(i, i + 4) for i in [2, 4, 6]])      #inner list treated as rows of the array
A1, A2

(array([0, 1, 2, 3, 4, 5, 6]),
 array([[2, 3, 4, 5],
        [4, 5, 6, 7],
        [6, 7, 8, 9]]))

### Creating arrays from scratch

In [57]:
#length-10 integer array filled with zeros. Default type is 'float'
np.zeros(10, dtype='int')     

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
#3x5 floating point array filled with ones

np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
#nxn array filled with 3.14

np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [64]:
#Create an array filled with a linear sequence
#Starting at 0, ending at 30, stepping by 3

np.arange(0,33,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [66]:
#array of n values evenly spaced between the given range

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [83]:
#random

R1 = np.random.random((3,3))

#normally distributed random values with mean 0 and sd 1
R2 = np.random.normal(0,1,(3,3))

#3x3 random integers in an interval (0,5)
R3 = np.random.randint(0,5,(3,3))

R1, R2, R3

(array([[0.37921762, 0.58050435, 0.032851  ],
        [0.54430787, 0.82882261, 0.42906581],
        [0.0937307 , 0.94510424, 0.81066331]]),
 array([[-0.39799181,  0.25256795,  1.29621754],
        [-0.71226273, -1.24525111, -0.00200533],
        [-1.26984547, -1.39133288,  0.16880535]]),
 array([[1, 0, 0],
        [2, 0, 3],
        [1, 0, 1]]))

In [85]:
#crating identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Basics of NumPy arrays

### Attributes of Arrays

In [2]:
np.random.seed(0)   #seed to ensure that each time same random numbers are generating

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [3]:
print(x3.ndim)          #number of dimensions
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60


In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[::, ::-1]

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [28]:
x2[::, 0]

array([3, 7, 1])

In [29]:
x2[0]

array([3, 5, 2, 4])

### Numpy array slicing uses views instead of copying the subarrays

In [35]:
x2_sub = x2[:2, 1:4:2]
x2_sub

array([[5, 4],
       [6, 8]])

In [43]:
x2_sub[0, 1] = 99    #will change the original array. This default behavior is actually quite useful: it means that when we work with large datasets,
                     #we can access and process pieces of these datasets without the need to copy the underlying data buffer
x2

array([[ 3,  5,  2, 99],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### instead we can copy the array by copy() method

In [44]:
x2_sub_copy = x2[:2, 1:4:2].copy()
x2_sub_copy[0,1] = 40

x2    #will not changed

array([[ 3,  5,  2, 99],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])